### ISSUE TITLE
How can I rename the sample IDs of otu_table? 

### ISSUE THREAD

**Issue by Lashari37** [mikemc/phyloseqpp#13]
Hi there 

I need to rename the samples IDs of the otu_table to match the sample metadata for phyloseq object. From the below example, how can I rename sample "2D-RptA-16S-V3-V4" to a new name? How can I rename all the sample IDs with a single command? Please advise.  

sample_names(ps2fr1)
 [1] "2D-RptA-16S-V3-V4"  "3D-RptA-16S-V3-V4"  "17D-RptA-16S-V3-V4" "19D-RptA-16S-V3-V4"
 [5] "18D-RptA-16S-V3-V4" "10D-RptA-16S-V3-V4" "9D-RptA-16S-V3-V4"  "7D-RptA-16S-V3-V4" 
 [9] "8D-RptA-16S-V3-V4"  "6D-RptA-16S-V3-V4"  "5D-RptA-16S-V3-V4"  "4D-RptA-16S-V3-V4" 

Cheers
Jamal

**Comment by mikemc** [comment]
There are various R packages and functions that can do string manipulation. I like using the `stringr` package. But first you need to be able to explain the "recipe" of how you want to rename each string. So, for example, what do you want to rename "2D-RptA-16S-V3-V4" to?

**Comment by Lashari37** [comment]
Thanks @mikemc, From the given example, I want to rename "2D-RptA-16S-V3-V4" to according to the combination factor of tested treatment, like "MW.Time0". 

I tried str_replace_all() but couldn't get through. Could you please write code for a single sample? 
I need to rename the sample IDs in otu_table; therefore, I tried 

str_replace_all(phyloseq$out_table, --) but it didn't work.

**Comment by mikemc** [comment]
> From the given example, I want to rename "2D-RptA-16S-V3-V4" to according to the combination factor of tested treatment, like "MW.Time0". (...) Could you please write code for a single sample?

You have not given any indication where this information is stored. It is apparently not contained in the sample names themselves, so using a string replacement function will not work as I had originally thought. Is it in the sample data? Please try to provide all the relevant information when asking for code help, to make it as easy as possible for me / someone else to answer your question.
